# Generated by Django 6.0.2 on 2026-05-26 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_unit',
            field=models.CharField(choices=[('kg', 'Per Kg'), ('gram', 'Per Gram')], default='kg', max_length=10),
        ),
    ]
