# Generated by Django 6.0.2 on 2026-06-03 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_product_price_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='customer',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='customer_uploads/'),
        ),
    ]
