# Generated by Django 6.0.2 on 2026-06-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_customer_address_customer_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_person_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('order_processing', 'Order Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='order_processing', max_length=30),
        ),
    ]
