# Generated by Django 6.0.2 on 2026-06-05 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_order_delivery_person_name_order_delivery_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=255)),
                ('value', models.TextField(blank=True, default='')),
                ('setting_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('image', 'Image'), ('css', 'CSS'), ('html', 'HTML'), ('color', 'Color')], default='text', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
    ]
