# Generated by Django 6.0.2 on 2026-06-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_sitesetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='setting_type',
            field=models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('image', 'Image'), ('video', 'Video'), ('button', 'Button'), ('css', 'CSS'), ('html', 'HTML'), ('color', 'Color'), ('font', 'Font')], default='text', max_length=20),
        ),
    ]
